spring.application.name=FoodDeliveryBackend

server.port=8081

spring.datasource.url=jdbc:sqlserver://ZAIN\\SQLEXPRESS;databaseName=FoodDeliverySystem;encrypt=false;trustServerCertificate=true
spring.datasource.username=oms_app
spring.datasource.password=123qwe987poi
spring.datasource.driver-class-name=com.microsoft.sqlserver.jdbc.SQLServerDriver

spring.jpa.hibernate.ddl-auto=none

#spring.profiles.active=dev

spring.jpa.show-sql=true
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.SQLServerDialect
spring.jpa.properties.hibernate.format_sql=true
#spring.jpa.hibernate.naming.physical-strategy=org.hibernate.boot.model.naming.PhysicalNamingStrategyStandardImpl

jwt.secret=${JWT_SECRET}

spring.liquibase.enabled=true
spring.liquibase.url=jdbc:sqlserver://ZAIN\\SQLEXPRESS;databaseName=FoodDeliverySystem;encrypt=false;trustServerCertificate=true
spring.liquibase.user=oms_app
spring.liquibase.password=123qwe987poi
spring.liquibase.change-log=classpath:db/changelog/db.changelog-master.yaml


spring.security.oauth2.resourceserver.jwt.issuer-uri=http://localhost:8080/realms/food-delivery

app.keycloak.base-url=http://localhost:8080
app.keycloak.realm=food-delivery
app.keycloak.client-id=food-delivery-api

management.endpoints.web.exposure.include=*